# the amount of ticks to wait before each break cycle
break-delay: 0

# max amount of blocks that will be broken each break cycle
max-breaks-per-cycle: 100

# break mode
# classic: breaks logs only above the one you broke
# classic_with_leaves: classic, but breaks all leaves
# full: breaks all logs and leaves.
# full_without_leaves: breaks all logs.
mode: full_without_leaves

# id names for items that will be considered axes
axe-types:
  - wooden_axe
  - stone_axe
  - iron_axe
  - diamond_axe
  - golden_axe

# id names for blocks that will be considered logs
log-types:
  - oak_log
  - oak_wood
  - stripped_oak_log
  - stripped_oak_wood
  - spruce_log
  - spruce_wood
  - stripped_spruce_log
  - stripped_spruce_wood
  - birch_log
  - birch_wood
  - stripped_birch_log
  - stripped_birch_wood
  - jungle_log
  - jungle_wood
  - stripped_jungle_log
  - stripped_jungle_wood
  - acacia_log
  - acacia_wood
  - stripped_acacia_log
  - stripped_acacia_wood
  - dark_oak_log
  - dark_oak_wood
  - stripped_dark_oak_log
  - stripped_dark_oak_wood

# id names for blocks that will be considered leaves
leaves-types:
  - oak_leaves
  - spruce_leaves
  - birch_leaves
  - jungle_leaves
  - acacia_leaves
  - dark_oak_leaves
